site_name: Example course

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://insper-education.github.io/active-handout-example-course/
repo_url: https://github.com/insper-education/active-handout-example-course
edit_uri: edit/main/content/
repo_name: active-handout-example-course

nav:
  - Home: index.md
  - Classes:
    - classes/01-ExampleClass/index.md
  - Laboratories:
    - labs/01-ExampleLab/index.md
    - labs/02-DCMotor/index.md
    - labs/0-new-lab/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js
  - js/math.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

plugins: 
  - git-revision-date-localized
